// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    foodItems,
    foodAttributes,
    mealEntries,
    mealEntryItems,
    symptomTypes,
    symptomEntries,
    bowelEntries,
    weightEntries,
    waterEntries,
    sleepEntries,
    activityEntries,
    medications,
    medicationIntakes,
    fodmapChallenges,
    idxMealEntriesLocalDay,
    idxMealEntriesOccurredAt,
    idxSymptomEntriesLocalDay,
    idxSymptomEntriesOccurredAt,
    idxBowelEntriesLocalDay,
    idxBowelEntriesOccurredAt,
    idxWeightEntriesLocalDay,
    idxWeightEntriesOccurredAt,
    idxWaterEntriesLocalDay,
    idxWaterEntriesOccurredAt,
    idxSleepEntriesLocalDay,
    idxActivityEntriesLocalDay,
    idxActivityEntriesOccurredAt,
    idxMedicationIntakesLocalDay,
    idxMedicationIntakesOccurredAt,
    idxFodmapChallengesStartDay,
  ];
  late final Shape0 foodItems = Shape0(
    source: i0.VersionedTable(
      entityName: 'food_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foodAttributes = Shape1(
    source: i0.VersionedTable(
      entityName: 'food_attributes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(food_item_id, source, "key")',
      ],
      columns: [_column_0, _column_9, _column_10, _column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 mealEntries = Shape2(
    source: i0.VersionedTable(
      entityName: 'meal_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 mealEntryItems = Shape3(
    source: i0.VersionedTable(
      entityName: 'meal_entry_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_16, _column_17, _column_18],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 symptomTypes = Shape4(
    source: i0.VersionedTable(
      entityName: 'symptom_types',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK((preset_key IS NULL)!=(custom_name IS NULL))',
      ],
      columns: [_column_0, _column_19, _column_20, _column_21, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 symptomEntries = Shape5(
    source: i0.VersionedTable(
      entityName: 'symptom_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 bowelEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'bowel_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 weightEntries = Shape7(
    source: i0.VersionedTable(
      entityName: 'weight_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 waterEntries = Shape8(
    source: i0.VersionedTable(
      entityName: 'water_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 sleepEntries = Shape9(
    source: i0.VersionedTable(
      entityName: 'sleep_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 activityEntries = Shape10(
    source: i0.VersionedTable(
      entityName: 'activity_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_38,
        _column_36,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 medications = Shape11(
    source: i0.VersionedTable(
      entityName: 'medications',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 medicationIntakes = Shape12(
    source: i0.VersionedTable(
      entityName: 'medication_intakes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_46,
        _column_47,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 fodmapChallenges = Shape13(
    source: i0.VersionedTable(
      entityName: 'fodmap_challenges',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_49,
        _column_47,
        _column_43,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxMealEntriesLocalDay = i1.Index(
    'idx_meal_entries_local_day',
    'CREATE INDEX idx_meal_entries_local_day ON meal_entries (local_day)',
  );
  final i1.Index idxMealEntriesOccurredAt = i1.Index(
    'idx_meal_entries_occurred_at',
    'CREATE INDEX idx_meal_entries_occurred_at ON meal_entries (occurred_at)',
  );
  final i1.Index idxSymptomEntriesLocalDay = i1.Index(
    'idx_symptom_entries_local_day',
    'CREATE INDEX idx_symptom_entries_local_day ON symptom_entries (local_day)',
  );
  final i1.Index idxSymptomEntriesOccurredAt = i1.Index(
    'idx_symptom_entries_occurred_at',
    'CREATE INDEX idx_symptom_entries_occurred_at ON symptom_entries (occurred_at)',
  );
  final i1.Index idxBowelEntriesLocalDay = i1.Index(
    'idx_bowel_entries_local_day',
    'CREATE INDEX idx_bowel_entries_local_day ON bowel_entries (local_day)',
  );
  final i1.Index idxBowelEntriesOccurredAt = i1.Index(
    'idx_bowel_entries_occurred_at',
    'CREATE INDEX idx_bowel_entries_occurred_at ON bowel_entries (occurred_at)',
  );
  final i1.Index idxWeightEntriesLocalDay = i1.Index(
    'idx_weight_entries_local_day',
    'CREATE INDEX idx_weight_entries_local_day ON weight_entries (local_day)',
  );
  final i1.Index idxWeightEntriesOccurredAt = i1.Index(
    'idx_weight_entries_occurred_at',
    'CREATE INDEX idx_weight_entries_occurred_at ON weight_entries (occurred_at)',
  );
  final i1.Index idxWaterEntriesLocalDay = i1.Index(
    'idx_water_entries_local_day',
    'CREATE INDEX idx_water_entries_local_day ON water_entries (local_day)',
  );
  final i1.Index idxWaterEntriesOccurredAt = i1.Index(
    'idx_water_entries_occurred_at',
    'CREATE INDEX idx_water_entries_occurred_at ON water_entries (occurred_at)',
  );
  final i1.Index idxSleepEntriesLocalDay = i1.Index(
    'idx_sleep_entries_local_day',
    'CREATE INDEX idx_sleep_entries_local_day ON sleep_entries (local_day)',
  );
  final i1.Index idxActivityEntriesLocalDay = i1.Index(
    'idx_activity_entries_local_day',
    'CREATE INDEX idx_activity_entries_local_day ON activity_entries (local_day)',
  );
  final i1.Index idxActivityEntriesOccurredAt = i1.Index(
    'idx_activity_entries_occurred_at',
    'CREATE INDEX idx_activity_entries_occurred_at ON activity_entries (occurred_at)',
  );
  final i1.Index idxMedicationIntakesLocalDay = i1.Index(
    'idx_medication_intakes_local_day',
    'CREATE INDEX idx_medication_intakes_local_day ON medication_intakes (local_day)',
  );
  final i1.Index idxMedicationIntakesOccurredAt = i1.Index(
    'idx_medication_intakes_occurred_at',
    'CREATE INDEX idx_medication_intakes_occurred_at ON medication_intakes (occurred_at)',
  );
  final i1.Index idxFodmapChallengesStartDay = i1.Index(
    'idx_fodmap_challenges_start_day',
    'CREATE INDEX idx_fodmap_challenges_start_day ON fodmap_challenges (start_day)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get category =>
      columnsByName['category']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isFavorite =>
      columnsByName['is_favorite']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get usageCount =>
      columnsByName['usage_count']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastUsedAt =>
      columnsByName['last_used_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_favorite',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_favorite IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'usage_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_used_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get foodItemId =>
      columnsByName['food_item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_item_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES food_items(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealType =>
      columnsByName['meal_type']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'occurred_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealEntryId =>
      columnsByName['meal_entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get foodItemId =>
      columnsByName['food_item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get portionDescription =>
      columnsByName['portion_description']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'meal_entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES meal_entries(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'food_item_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES food_items(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'portion_description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get presetKey =>
      columnsByName['preset_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customName =>
      columnsByName['custom_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'preset_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'custom_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get symptomTypeId =>
      columnsByName['symptom_type_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get intensity =>
      columnsByName['intensity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMinutes =>
      columnsByName['duration_minutes']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'symptom_type_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES symptom_types(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'intensity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (intensity BETWEEN 1 AND 10)',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_minutes',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get bristolType =>
      columnsByName['bristol_type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get urgency =>
      columnsByName['urgency']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pain =>
      columnsByName['pain']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get blood =>
      columnsByName['blood']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mucus =>
      columnsByName['mucus']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get incompleteEvacuation =>
      columnsByName['incomplete_evacuation']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'bristol_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (bristol_type BETWEEN 1 AND 7)',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'urgency',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (urgency IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'pain',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (pain BETWEEN 1 AND 10)',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'blood',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (blood IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'mucus',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (mucus IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'incomplete_evacuation',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (incomplete_evacuation IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get weightKg =>
      columnsByName['weight_kg']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_31(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'weight_kg',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get amountMl =>
      columnsByName['amount_ml']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amount_ml',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bedAt =>
      columnsByName['bed_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wokeAt =>
      columnsByName['woke_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMinutes =>
      columnsByName['duration_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get quality =>
      columnsByName['quality']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'local_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'bed_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'woke_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_minutes',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_37(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quality',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (quality BETWEEN 1 AND 5)',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get activityName =>
      columnsByName['activity_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get durationMinutes =>
      columnsByName['duration_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get effort =>
      columnsByName['effort']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'activity_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'effort',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get dosage =>
      columnsByName['dosage']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scheduleType =>
      columnsByName['schedule_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scheduledTimes =>
      columnsByName['scheduled_times']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startDay =>
      columnsByName['start_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get endDay =>
      columnsByName['end_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'dosage',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'schedule_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scheduled_times',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'start_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'end_day',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_active',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (is_active IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get localDay =>
      columnsByName['local_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get medicationId =>
      columnsByName['medication_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scheduledTime =>
      columnsByName['scheduled_time']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'medication_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES medications(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scheduled_time',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get fodmapGroup =>
      columnsByName['fodmap_group']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get startDay =>
      columnsByName['start_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get testEndDay =>
      columnsByName['test_end_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get completedDay =>
      columnsByName['completed_day']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get outcome =>
      columnsByName['outcome']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get outcomeNote =>
      columnsByName['outcome_note']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'fodmap_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'test_end_day',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'completed_day',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'outcome',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'outcome_note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    foodItems,
    foodAttributes,
    mealEntries,
    mealEntryItems,
    symptomTypes,
    symptomEntries,
    bowelEntries,
    weightEntries,
    waterEntries,
    sleepEntries,
    activityEntries,
    medications,
    medicationIntakes,
    fodmapChallenges,
    idxMealEntriesLocalDay,
    idxMealEntriesOccurredAt,
    idxSymptomEntriesLocalDay,
    idxSymptomEntriesOccurredAt,
    idxBowelEntriesLocalDay,
    idxBowelEntriesOccurredAt,
    idxWeightEntriesLocalDay,
    idxWeightEntriesOccurredAt,
    idxWaterEntriesLocalDay,
    idxWaterEntriesOccurredAt,
    idxSleepEntriesLocalDay,
    idxActivityEntriesLocalDay,
    idxActivityEntriesOccurredAt,
    idxMedicationIntakesLocalDay,
    idxMedicationIntakesOccurredAt,
    idxFodmapChallengesStartDay,
  ];
  late final Shape0 foodItems = Shape0(
    source: i0.VersionedTable(
      entityName: 'food_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 foodAttributes = Shape1(
    source: i0.VersionedTable(
      entityName: 'food_attributes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(food_item_id, source, "key")',
      ],
      columns: [_column_0, _column_9, _column_10, _column_11, _column_12],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 mealEntries = Shape2(
    source: i0.VersionedTable(
      entityName: 'meal_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_15,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 mealEntryItems = Shape14(
    source: i0.VersionedTable(
      entityName: 'meal_entry_items',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_16, _column_17, _column_18, _column_54],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 symptomTypes = Shape4(
    source: i0.VersionedTable(
      entityName: 'symptom_types',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'CHECK((preset_key IS NULL)!=(custom_name IS NULL))',
      ],
      columns: [_column_0, _column_19, _column_20, _column_21, _column_1],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 symptomEntries = Shape5(
    source: i0.VersionedTable(
      entityName: 'symptom_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 bowelEntries = Shape6(
    source: i0.VersionedTable(
      entityName: 'bowel_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 weightEntries = Shape7(
    source: i0.VersionedTable(
      entityName: 'weight_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_31,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 waterEntries = Shape8(
    source: i0.VersionedTable(
      entityName: 'water_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 sleepEntries = Shape9(
    source: i0.VersionedTable(
      entityName: 'sleep_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 activityEntries = Shape10(
    source: i0.VersionedTable(
      entityName: 'activity_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_38,
        _column_36,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 medications = Shape11(
    source: i0.VersionedTable(
      entityName: 'medications',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_8,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 medicationIntakes = Shape12(
    source: i0.VersionedTable(
      entityName: 'medication_intakes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_13,
        _column_14,
        _column_8,
        _column_46,
        _column_47,
        _column_48,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 fodmapChallenges = Shape13(
    source: i0.VersionedTable(
      entityName: 'fodmap_challenges',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_49,
        _column_47,
        _column_43,
        _column_50,
        _column_51,
        _column_52,
        _column_53,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxMealEntriesLocalDay = i1.Index(
    'idx_meal_entries_local_day',
    'CREATE INDEX idx_meal_entries_local_day ON meal_entries (local_day)',
  );
  final i1.Index idxMealEntriesOccurredAt = i1.Index(
    'idx_meal_entries_occurred_at',
    'CREATE INDEX idx_meal_entries_occurred_at ON meal_entries (occurred_at)',
  );
  final i1.Index idxSymptomEntriesLocalDay = i1.Index(
    'idx_symptom_entries_local_day',
    'CREATE INDEX idx_symptom_entries_local_day ON symptom_entries (local_day)',
  );
  final i1.Index idxSymptomEntriesOccurredAt = i1.Index(
    'idx_symptom_entries_occurred_at',
    'CREATE INDEX idx_symptom_entries_occurred_at ON symptom_entries (occurred_at)',
  );
  final i1.Index idxBowelEntriesLocalDay = i1.Index(
    'idx_bowel_entries_local_day',
    'CREATE INDEX idx_bowel_entries_local_day ON bowel_entries (local_day)',
  );
  final i1.Index idxBowelEntriesOccurredAt = i1.Index(
    'idx_bowel_entries_occurred_at',
    'CREATE INDEX idx_bowel_entries_occurred_at ON bowel_entries (occurred_at)',
  );
  final i1.Index idxWeightEntriesLocalDay = i1.Index(
    'idx_weight_entries_local_day',
    'CREATE INDEX idx_weight_entries_local_day ON weight_entries (local_day)',
  );
  final i1.Index idxWeightEntriesOccurredAt = i1.Index(
    'idx_weight_entries_occurred_at',
    'CREATE INDEX idx_weight_entries_occurred_at ON weight_entries (occurred_at)',
  );
  final i1.Index idxWaterEntriesLocalDay = i1.Index(
    'idx_water_entries_local_day',
    'CREATE INDEX idx_water_entries_local_day ON water_entries (local_day)',
  );
  final i1.Index idxWaterEntriesOccurredAt = i1.Index(
    'idx_water_entries_occurred_at',
    'CREATE INDEX idx_water_entries_occurred_at ON water_entries (occurred_at)',
  );
  final i1.Index idxSleepEntriesLocalDay = i1.Index(
    'idx_sleep_entries_local_day',
    'CREATE INDEX idx_sleep_entries_local_day ON sleep_entries (local_day)',
  );
  final i1.Index idxActivityEntriesLocalDay = i1.Index(
    'idx_activity_entries_local_day',
    'CREATE INDEX idx_activity_entries_local_day ON activity_entries (local_day)',
  );
  final i1.Index idxActivityEntriesOccurredAt = i1.Index(
    'idx_activity_entries_occurred_at',
    'CREATE INDEX idx_activity_entries_occurred_at ON activity_entries (occurred_at)',
  );
  final i1.Index idxMedicationIntakesLocalDay = i1.Index(
    'idx_medication_intakes_local_day',
    'CREATE INDEX idx_medication_intakes_local_day ON medication_intakes (local_day)',
  );
  final i1.Index idxMedicationIntakesOccurredAt = i1.Index(
    'idx_medication_intakes_occurred_at',
    'CREATE INDEX idx_medication_intakes_occurred_at ON medication_intakes (occurred_at)',
  );
  final i1.Index idxFodmapChallengesStartDay = i1.Index(
    'idx_fodmap_challenges_start_day',
    'CREATE INDEX idx_fodmap_challenges_start_day ON fodmap_challenges (start_day)',
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mealEntryId =>
      columnsByName['meal_entry_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get foodItemId =>
      columnsByName['food_item_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get portionDescription =>
      columnsByName['portion_description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get quantity =>
      columnsByName['quantity']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<double> _column_54(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'quantity',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
